baseurl: ''
exclude: [ 'dev-docker.sh', 'feed.xml' ]
permalink: /posts/:title.html

logo: /img/favicons/favicon-96x96.png
cover: /img/cover.jpeg

title: jdrydn
url: 'https://jdrydn.com'

google_analytics: UA-28506039-1

description: |
  *If I have to do something more than once I'm writing a script for it.*

  **Engineer** at heart, often found working on greenfield projects and/or microservices in
  **NodeJS** (*ExpressJS, ~~Koa~~*) ~~or **PHP** (*Symphony*)~~,
  familiar with **relational databases** (*MySQL, Postgres*),
  **document-driven databases** (*MongoDB, ~RethinkDB~, Elasticsearch*),
  **templating** (*Handlebars, ~~Nunjucks,~~ Jekyll, Liquid, ~~Jade~~ Pug*),
  **unit testing** with code-coverage (*Mocha, Istanbul, ~~PHPUnit~~*),
  **logging infrastructures** (*Fluentd, Kibana*),
  as well as **dev-ops roles** (*dedicated servers, Docker, AWS*).

  Currently working as the **CTO** of [Real Links](https://www.reallinks.io/) üöÄ

  Formerly [Muzmatch](https://muzmatch.com/) üéà,
  [Car Throttle](https://www.carthrottle.com)/[WTF1](https://wtf1.com/) üèé and
  [MyVoucherCodes](https://www.myvouchercodes.co.uk/) üè∑

defaults:
  - scope:
      path: ''
    values:
      author: james

authors:
  james:
    name: James D
    image: /img/author-james.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/jdrydn
    desc: Follow me on twitter

  - icon:	github
    url:	https://github.com/jdrydn
    desc:	Fork me on github

# footer:
#   - url: /about
#     label: About
