baseurl: ''
exclude: [ 'dev-docker.sh', 'feed.xml' ]
permalink: /posts/:title.html

logo: /img/favicons/favicon-96x96.png
cover: /img/cover.jpeg

title: jdrydn
tagline: |
  *Don't be down, server. We all think you're doing a great job & everyone likes you!*
url: 'https://jdrydn.com'

google_analytics: UA-28506039-1

description: |
  **Engineer** at heart, often found working on greenfield projects and/or microservices in
  **NodeJS** (*ExpressJS, Serverless, ~~Koa~~*) ~~or **PHP** (*Symphony*)~~,
  familiar with **relational databases** (*MySQL, Postgres*),
  **document-driven databases** (*MongoDB, ~~RethinkDB,~~ Elasticsearch*),
  **templating** (*Handlebars, ~~Nunjucks,~~ Jekyll, Liquid, ~~Jade~~ Pug*),
  **unit testing** with code-coverage (*Mocha, Istanbul, ~~PHPUnit~~*),
  **logging infrastructures** (*Fluentd, Kibana*),
  as well as **devops roles** (*dedicated servers, Docker, AWS*).

  *Give me a container over a server any day.*

  Currently working as the **CTO** of ğŸš€[Real Links](https://www.reallinks.io/).
  Formerly ğŸˆ[Muzmatch](https://muzmatch.com/),
  ğŸ[Car Throttle](https://www.carthrottle.com)/[WTF1](https://wtf1.com/) and
  ğŸ·[MyVoucherCodes](https://www.myvouchercodes.co.uk/).

defaults:
  - scope:
      path: ''
    values:
      author: james

authors:
  james:
    name: James D
    image: /img/author-james.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/jdrydn
    desc: Follow me on twitter

  - icon:	github
    url:	https://github.com/jdrydn
    desc:	Fork me on github
